apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: inference-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/javiagu13/Kubernetes-Argo-CI-CD-ML.git
    targetRevision: HEAD
    path: inference-api

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true