apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: inference-api-error-rate
spec:
  args:
    - name: canary-hash

  metrics:
    - name: canary-error-rate
      interval: 15s
      initialDelay: 15s
      count: 5
      failureLimit: 2

      successCondition: result[0] < 0.25

      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc.cluster.local:9090

          query: |
            (
              sum(
                rate(
                  http_requests_total{
                    namespace="default",
                    service="inference-api",
                    handler="/predict",
                    method="POST",
                    status=~"5..",
                    pod=~"inference-api-{{ `{{args.canary-hash}}` }}-.*"
                  }[1m]
                )
              )
            )
            /
            (
              sum(
                rate(
                  http_requests_total{
                    namespace="default",
                    service="inference-api",
                    handler="/predict",
                    method="POST",
                    pod=~"inference-api-{{ `{{args.canary-hash}}` }}-.*"
                  }[1m]
                )
              )
            )