apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "inference-api.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "inference-api.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "inference-api.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: inference-api

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: VERSION
              value: "{{ .Values.env.VERSION }}"

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5

          resources:
            {{- toYaml .Values.resources | nindent 12 }}